<?php

/**
 * Created by PhpStorm.
 * User: lixianjun
 * Date: 2019/4/24
 * Time: 15:43
 */

namespace app\admin\controller;


use app\admin\Common;

class Order extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_checkLogin();
    }


    public function add(){
        $this->assign('title',  '添加订单');

        return $this->fetch('add');
    }

    /**
     * 列表，带搜索
     * @author lixianjun
     * @return mixed
     * Date: 2019/4/24
     * Time: 16:54
     */
    public function list(){
        $this->assign('title', '订单列表');

        return $this->fetch('list');
    }

}