<?php

/**
 * Created by PhpStorm.
 * User: lixianjun
 * Date: 2019/4/24
 * Time: 16:50
 */

namespace app\admin\controller;


use app\admin\Common;

class Orderapi extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_checkLogin();
    }

    /**
     * 删除
     * @author lixianjun
     * Date: 2019/4/24
     * Time: 16:51
     */
    public function delete(){

    }

    /**
     * 支付
     * @author lixianjun
     * Date: 2019/4/24
     * Time: 16:51
     */
    public function pay(){

    }

    /**
     * 重置支付
     * @author lixianjun
     * Date: 2019/4/24
     * Time: 16:51
     */
    public function repay(){

    }


}