<?php

/**
 * Created by PhpStorm.
 * User: lixianjun
 * Date: 2019/4/15
 * Time: 11:30
 */

namespace app\admin\controller;


use app\admin\Common;
use app\admin\logic\SendMsg;
use think\Request;

class SendmsgShow extends Common
{
    public function _initialize()
    {
        $this->_checkLogin();
//        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function sendShow()
    {
        $this->assign('title', '发送短信');
        return $this->fetch('sendshow');
    }

    /**
     * 提交
     * @author lixianjun
     * @return \think\Response
     * Date: 2019/4/15
     * Time: 15:03
     */
    public function submit()
    {
        if (\request()->isPost()) {
            $params = $this->request->only(['name', 'phone', 'date', 'number', 'post', 'city']);
            $obj = new SendMsg();
            $result = $obj->addMsg($params, $this->userInfo['id']);
            return $this->sendSuccess($result);
        }else{
            echo '请求错误';
            exit;
        }
    }

    public function getList(){
        $obj = new SendMsg();
        $params = $this->request->only([]);
        $result = $obj->getMsgDatas($params);
        return $this->sendSuccess($result);
    }

    public function historyShow()
    {
        $this->assign('title', '查看历史记录');
        $obj = new SendMsg();
        $params = $this->request->only([]);
        $datas = $obj->getMsgDatas($params);
        // 模板变量赋值
        $this->assign('page', $datas->render());
        $this->assign('data', $datas);
        return $this->fetch('historyshow');
    }

}