<?php

/**
 * Created by PhpStorm.
 * User: lixianjun
 * Date: 2019/4/15
 * Time: 11:30
 */

namespace app\admin\controller;



use app\admin\Common;
use app\admin\logic\SendMsg;

class SendmsgShow extends Common
{
    public function _initialize()
    {
        $this->_checkLogin();
//        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function sendShow(){
        $this->assign('title', '发送短信');
        return $this->fetch('sendshow');
    }

    /**
     * 提交
     * @author lixianjun
     * @return \think\Response
     * Date: 2019/4/15
     * Time: 15:03
     */
    public function submit(){
        $params = $this->request->only(['name', 'phone', 'date', 'number', 'post']);
        $obj = new SendMsg();
        $result = $obj->addMsg($params);
        return $this->sendSuccess($result);
    }

    public function historyShow(){
        $this->assign('title', '查看已发送');
        return $this->fetch('historyshow');
    }

}